export const UPLOAD_ARCHIVE = 'UPLOAD_ARCHIVE';
export const UPLOAD_YAML = 'UPLOAD_YAML';
export const SET_SCHEMA = 'SET_SCHEMA';
export const EXPORT_DESCRIPTOR = 'EXPORT_DESCRIPTOR';
export const DESCRIPTOR_CHANGE = 'DESCRIPTOR_CHANGE';
export const VALIDATE = 'VALIDATE';
export const SHOW_ALERT = 'SHOW_ALERT';
export const CLOSE_ALERT = 'CLOSE_ALERT';
export const ONBOARD_VNF = 'ONBOARD_VNF';
export const ONBOARD_NSD = 'ONBOARD_NSD';
export const RESET = 'RESET';
export const SET_DESCRIPTOR_TYPE = 'SET_DESCRIPTOR_TYPE';
export const UPLOAD_ARCHIVE_FAIL = 'UPLOAD_ARCHIVE_FAIL';
export const SETISVNFD = 'SETISVNFD';

export const CLEAR_LOGS = 'CLEAR_LOGS';
export const SET_SERVICE_NAME = 'SET_SERVICE_NAME';
export const SET_PORTS = 'SET_PORTS';
export const SET_INVALID_STATUS = 'SET_INVALID_STATUS';
export const SET_IP_ADDRESS = 'SET_IP_ADDRESS';
export const SET_IP_INVALID_STATUS = 'SET_IP_INVALID_STATUS';
export const SET_PROFILE_TYPE = 'SET_PROFILE_TYPE';
export const SET_NFP_CONF = 'SET_NFP_CONF';
export const SET_NFP_CONF_ERROR = 'SET_NFP_CONF_ERROR';
export const SET_NFC_CONF = 'SET_NFC_CONF';
export const SET_NFC_CONF_ERR = 'SET_NFC_CONF_ERR';
export const SET_FP_CONF = 'SET_FP_CONF';
export const SET_FP_CONF_ERR = 'SET_FP_CONF_ERR';
export const SET_INPUT_CHANGES = 'SET_INPUT_CHANGES';
export const START_PROFILER = 'START_PROFILER';
export const START_PROFILER_FAIL = 'START_PROFILER_FAIL';
export const START_PROFILER_LOG = 'START_PROFILER_LOG';
export const START_PROFILER_LOG_FAIL = 'START_PROFILER_LOG_FAIL';

export const SET_LEAN_PROCESS_ID = 'SET_LEAN_PROCESS_ID';
export const SET_OSM_PROCESS_ID = 'SET_OSM_PROCESS_ID';

export const SET_REPO_NAME = 'SET_REPO_NAME';
export const SET_OPERATION_INDEX = 'SET_OPERATION_INDEX';
export const SET_PACKAGE_YAML = 'SET_PACKAGE_YAML';
export const SET_RUN_YAML = 'SET_RUN_YAML';
export const SET_LOADING = 'SET_LOADING';
export const CREATE_UNIKERNEL_PROJECT_SUCCESS =
  'CREATE_UNIKERNEL_PROJECT_SUCCESS';
export const CREATE_UNIKERNEL_PROJECT_FAIL = 'CREATE_UNIKERNEL_PROJECT_FAIL';
export const CLOSE_PACKAGING_ALERT = 'CLOSE_PACKAGING_ALERT';
export const CREATE_DOCKER_PROJECT_SUCCESS = 'CREATE_DOCKER_PROJECT_SUCCESS';
export const CREATE_DOCKER_PROJECT_FAIL = 'CREATE_DOCKER_PROJECT_FAIL';
export const GET_REPOS_WITH_TOKEN_SUCCESS = 'GET_REPOS_WITH_TOKEN_SUCCESS';
export const GET_REPOS_WITH_TOKEN_FAIL = 'GET_REPOS_WITH_TOKEN_FAIL';
export const SET_ACTIVE_REPO = 'SET_ACTIVE_REPO';
export const SET_SELECTED_PROJECT_TYPE = 'SET_SELECTED_PROJECT_TYPE';
export const SET_USER_LIST = 'SET_USER_LIST';
export const SET_BUILD_STATUS_LOADING = 'SET_BUILD_STATUS_LOADING';
export const GET_BUILD_STATUS_SUCCESS = 'GET_BUILD_STATUS_SUCCESS';
export const GET_BUILD_STATUS_FAIL = 'GET_BUILD_STATUS_FAIL';
export const SET_BUILD_BUTTON_LOADING = 'SET_BUILD_BUTTON_LOADING';
export const BUILD_PROJECT_SUCCESS = 'BUILD_PROJECT_SUCCESS';
export const BUILD_PROJECT_FAIL = 'BUILD_PROJECT_FAIL';

export const GET_ISSUES_SUCCESS = 'GET_ISSUES_SUCCESS';
export const GET_ISSUES_FAIL = 'GET_ISSUES_FAIL';

export const DELETE_ISSUES_SUCCESS = 'DELETE_ISSUES_SUCCESS';
export const DELETE_ISSUES_FAIL = 'DELETE_ISSUES_FAIL';
export const UPDATE_ISSUE_LIST = 'UPDATE_ISSUE_LIST';
export const SET_DELETE_LOADING = 'SET_DELETE_LOADING';
export const SET_DESCRIPTOR_FROM_LOGGING = 'SET_DESCRIPTOR_FROM_LOGGING';

export const GET_VNFD_LIST_SUCCESS = 'GET_VNFD_LIST_SUCCESS';
export const GET_VNFD_CONTENT_SUCCESS = 'GET_VNFD_CONTENT_SUCCESS';
export const GET_VNFD_LIST_FAIL = 'GET_VNFD_LIST_FAIL';
export const GET_VNFD_CONTENT_FAIL = 'GET_VNFD_CONTENT_FAIL';
