global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

#####################
# Cadvisor Exporter #
#####################

  - job_name:   'hostname'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['xxx.xxx.xxx.xxx:9911']
        labels:
          group: 'cAdvisor'
