version: "3"

services:
  cadvisor:
      image: google/cadvisor 
      container_name: cadvisor
      volumes:
         - /:/rootfs:ro
         - /var/run:/var/run:rw
         - /sys:/sys:ro
         - /var/lib/docker/:/var/lib/docker:ro
         - /cgroup:/cgroup:ro
      ports:
         - 9911:8080
      privileged: true
      restart: always
  prometheus:
      container_name: prometheus
      image: prom/prometheus:v1.7.1
      command: 
       - '-config.file=/etc/prometheus/prometheus.yml'
       - '-web.external-url=http://prometheus:9090/' 
       - '-web.route-prefix=/' 
      restart: always
      ports:
          - "9099:9090"
      volumes:
          - ./prometheusdata:/etc/prometheus:rw
          - ./prometheusdb:/prometheus/data:rw